### PR TITLE
Display Author Name on Images

### LINKED ISSUE #1: Need to show author name along with images.
I want to show the username of the authors of images in the app, but can't find a way to do it, because it needs another api call to find the author.

image

### PR DESCRIPTION
**Pull request by TheRealDust**
Author name is now displayed on each image, and slightly reworked some old code to make it easier to add to in future.

Closes #1

### CODE REVIEW

**Review by asrvd — APPROVED** [review]

**Comment by asrvd** [comment]
@TheRealDust apparently, I got rate limited for some reason, can you check the preview to see if the onclick event works, what could be the reason for ratelimit though, I think getting the author data is increasing the api call a lot causing rate limits, maybe we need to find some other way.
image

**Comment by TheRealDust** [comment]
> @TheRealDust apparently, I got rate limited for some reason, can you check the preview to see if the onclick event works, what could be the reason for ratelimit though, I think getting the author data is increasing the api call a lot causing rate limits, maybe we need to find some other way. image

I've just seen the click to open user page code you added, it completely slipped my mind while writing the original commits. My most recent commit to this branch fixed a problem where it tried to open all author github pages whenever the page reloaded/was opened.

I'm really not sure why you're experiencing rate limiting, I haven't been able to recreate it and neither has another friend who I had test this when you brought it up. I think the best solution would be to either get the author data in bulk rather than separate calls, but I'd have to look into whether that can be done with the api we're using, or to cache the author data on the client, which would really only help if the user was rapidly switching between pages. I'll do my best to solve this problem but again I haven't been able to recreate it so I might need to rely on you for testing at some point.

**Comment by asrvd** [comment]
> > @TheRealDust apparently, I got rate limited for some reason, can you check the preview to see if the onclick event works, what could be the reason for ratelimit though, I think getting the author data is increasing the api call a lot causing rate limits, maybe we need to find some other way. image
> 
> I've just seen the click to open user page code you added, it completely slipped my mind while writing the original commits. My most recent commit to this branch fixed a problem where it tried to open all author github pages whenever the page reloaded/was opened.
> 
> I'm really not sure why you're experiencing rate limiting, I haven't been able to recreate it and neither has another friend who I had test this when you brought it up. I think the best solution would be to either get the author data in bulk rather than separate calls, but I'd have to look into whether that can be done with the api we're using, or to cache the author data on the client, which would really only help if the user was rapidly switching between pages. I'll do my best to solve this problem but again I haven't been able to recreate it so I might need to rely on you for testing at some point.

would have been much easier if github provided the author data along with file, but nevermind that, I have actually a solution in mind, we can just keep this code only and rather use a github token, we get 60 requests per hour right now but if we implement a token, we will be getting 5000 requests per hour which would be more than sufficient ig, what do you think?

**Comment by asrvd** [comment]
@TheRealDust I just tried the preview app again, and yes it will surely rate limit anyone once they change the language, the app already exceeds the rate limits on the second call when someone changes language, so it just loads the image but isn't able to get author data. we need to increase requests or use some other method surely.

Edit: I've sent you an invite to join as collaborator on this repo if you want to.

**Comment by TheRealDust** [comment]
> would have been much easier if github provided the author data along with file, but nevermind that, I have actually a solution in mind, we can just keep this code only and rather use a github token, we get 60 requests per hour right now but if we implement a token, we will be getting 5000 requests per hour which would be more than sufficient ig, what do you think?

Implementing a token would definitely be a good idea in terms of reducing the rate limiting, but I don't think I can add the token to the server so you might have to write that bit. In terms of using another method to get author data, I'll look into getting it in bulk and/or caching it but again I'm not sure whether that would completely solve the problem or if it's even possible in the first place.

**Comment by asrvd** [comment]
> > would have been much easier if github provided the author data along with file, but nevermind that, I have actually a solution in mind, we can just keep this code only and rather use a github token, we get 60 requests per hour right now but if we implement a token, we will be getting 5000 requests per hour which would be more than sufficient ig, what do you think?
> 
> Implementing a token would definitely be a good idea in terms of reducing the rate limiting, but I don't think I can add the token to the server so you might have to write that bit. In terms of using another method to get author data, I'll look into getting it in bulk and/or caching it but again I'm not sure whether that would completely solve the problem or if it's even possible in the first place.

alright, so I did some math, and ig even if we have 5000 requests the maximum number of times someone would be able to change language is around 10 which is far less than current which is around 30. I don't think it would be efficient to add author like this, instead we can just add a link to the file in github as we don't need to make an extra api request for it, what do you think?

**Comment by TheRealDust** [comment]
> alright, so I did some math, and ig even if we have 5000 requests the maximum number of times someone would be able to change language is around 10 which is far less than current which is around 30. I don't think it would be efficient to add author like this, instead we can just add a link to the file in github as we don't need to make an extra api request for it, what do you think?

The code already has the relevant url attached to each image from memory so that should be fairly easy to implement. In regards to what you were saying, I can see some ways of maybe reducing the number of api calls, either by doing multiple images in the same call, or maybe somehow finding sets of images with the same author to reduce calls (not sure if that would even work, I'd have to look into it) but I'm not sure that would really *solve* the problem. For now I think you're right and we should just implement a "view commit" button or something, and consider coming back to this in future. I'll get onto adding that feature.

**Comment by asrvd** [comment]
> > alright, so I did some math, and ig even if we have 5000 requests the maximum number of times someone would be able to change language is around 10 which is far less than current which is around 30. I don't think it would be efficient to add author like this, instead we can just add a link to the file in github as we don't need to make an extra api request for it, what do you think?
> 
> The code already has the relevant url attached to each image from memory so that should be fairly easy to implement. In regards to what you were saying, I can see some ways of maybe reducing the number of api calls, either by doing multiple images in the same call, or maybe somehow finding sets of images with the same author to reduce calls (not sure if that would even work, I'd have to look into it) but I'm not sure that would really _solve_ the problem. For now I think you're right and we should just implement a "view commit" button or something, and consider coming back to this in future. I'll get onto adding that feature.

yes, i think that would be the correct thing to do, I'll close the issue for now too, and about getting the file url, we can get it from the `get_cont()` method in api.js.
image

**Comment by asrvd** [comment]
@TheRealDust should i go ahead and implement this or are you working on it?

**Comment by TheRealDust** [comment]
> @TheRealDust should i go ahead and implement this or are you working on it?

Yeah sorry go ahead with that. I've been a bit busy in the past couple of days so I didn't get around to implementing that.

**Comment by asrvd** [comment]
alright, np

**Pull request closed without merging**
