### PR TITLE
Added a static Image Background color

### PR DESCRIPTION
**Pull request by TheRealDust**
This gives all images a colored background which displays while they render. This is **not** a loading screen, but a true loading menu is somewhat difficult to implement, so this should make the site look a little better until then. 

Related Issue: #5

### CODE REVIEW

**Comment by asrvd** [comment]
looks good, but can we implement skeleton css here, i want them all to load at the same time 🤔

**Comment by TheRealDust** [comment]
> looks good, but can we implement skeleton css here, i want them all to load at the same time 🤔

Having a true skeleton would be the preferred option, only problem is that to do that well I might need to slightly restructure the image loading code. Should look the same on the front-end but might mean back-end has to be a *little bit* different, but I don't think it would cause any major problems. You'll be able to see for yourself if and when I finish the code 👍

**Comment by TheRealDust** [comment]
Pull Request Invalid, new version coming soon (tm)

**Comment by asrvd** [comment]
> > looks good, but can we implement skeleton css here, i want them all to load at the same time 🤔
> 
> Having a true skeleton would be the preferred option, only problem is that to do that well I might need to slightly restructure the image loading code. Should look the same on the front-end but might mean back-end has to be a _little bit_ different, but I don't think it would cause any major problems. You'll be able to see for yourself if and when I finish the code 👍

maybe we can implement [this](https://chakra-ui.com/docs/feedback/skeleton) cus, we can use a state here to define if image is all images are loaded or not, one solution could be to cache all image links in local storage and load them,

**Pull request closed without merging**
